AI LAB-1 (04/07/2023)
Exploring numpy

In [10]:
import numpy as np
a=np.array([1,2,3])
b=np.array([(1,2,3),(4,5,6)],dtype=float)
print("dimension:",a.ndim,"datatype:",a.dtype,"size:",a.size)
print("dimension:",b.ndim,"datatype:",b.dtype,"size:",b.size,"rows & columns:",b.shape)
b1=b.reshape(3,2)
print(b1)

dimension: 1 datatype: int64 size: 3
dimension: 2 datatype: float64 size: 6 rows & columns: (2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [14]:
import numpy as np
a=np.array([4,5,6,3,9,7])
b=np.array([(1, 2, 3),(4, 5, 6)])
print(a[2:5])
print(b[0,0:2])

[6 3 9]
[1 2]


In [18]:
import numpy as np
a=([4,5,6,7])
b=([3,4,1])
c=a+b
print(c)

a2=np.array([(1, 2, 3),(4, 5, 6)])
b2=np.array([(5,0,7),(6,2,1)])
c2=np.concatenate((a2,b2),axis=0)
print(c2)

[4, 5, 6, 7, 3, 4, 1]
[[1 2 3]
 [4 5 6]
 [5 0 7]
 [6 2 1]]


In [28]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 4, 4])
print(np.where(a == 4))

b=np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
print(np.where(b == 5))

c=np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("odd:",np.where(c%2!=0))
print("even:",np.where(c%2==0))

(array([3, 5, 6]),)
(array([1]), array([1]))
odd: (array([0, 2, 4, 6]),)
even: (array([1, 3, 5, 7]),)


In [30]:
import numpy as np
a=np.array([6, 5, 1, 2, 9, 10, 36, 7])
print(a.sort())

None
